feature: 공지사항 api 연결
Team-Offroad/Offroad-Android pull request #195
Opened 2024-09-23 06:01 UTC by leeseokchan00

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #190 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 공지사항 api 연결
- 로그아웃, 회원탈퇴 다이얼로그 수정

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/deb698d2-62b4-4560-9ebc-bcb0c1fe9299

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-09-23 15:43 UTC, junseo511 approved these changes
고생 많으셨어요 😘

2024-09-23 15:43 UTC, junseo511 commented on core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
> +        val updateAt: String,
c: updateAt이 어디에서 업데이트가 되었는지를 알려주는 변수인가요?

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
> +    ): GetAnnouncementUseCase {
r: 함수명하고 반환값 이름이 다른듯요

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/AnnouncementMapper.kt
> +    run {
c: 그냥 반환하지 않고 run을 쓰신 이유가 있나요?

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/AnnouncementResponseDto.kt
> +
r: 줄바꿈

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/AnnouncementResponseDto.kt
> +
r: 여기도

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/AnnouncementRepositoryImpl.kt
> +    }
r: 뷰모델이 아닌 레포지토리 단계에서 직접 네트워크 통신을 하는 이유가 있나요?

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/AnnouncementRepository.kt
> +    suspend fun getAnnouncement(): Result<List<Announcement>?>
c: nullable하게 두신 이유가 있으실까요?

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/AnnouncementRepository.kt
> +    suspend fun getAnnouncement(): Result<List<Announcement>?>
c: 단순 반환값이 아닌 Result로 감싸주시는 이유가 있나요? 프로젝트에 전반적으로 Result 쓴게 거의 없을텐데...?!

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
> +    return Triple(year, month, day)
a: 코틀린스럽고 좋네요 👍

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementViewModel.kt
> +    fun getAnnouncement() {
r: list를 받아오는 함수명에 적절한가요?

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementViewModel.kt
> +    fun getAnnouncement() {
r: 함수의 동작은 get이 아닌 라이브데이터의 값을 업데이트 해주고 있어요

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
> +        if (text == "오프로드 회원을 탈퇴하겠습니다.") {
r: string 추출해주세요!

2024-09-23 15:43 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
> +        }
c: when 문으로 쓰시는게 좀 더 간결할지도요?

2024-09-23 15:44 UTC, junseo511 requested changes
아 실수로 어푸눌렀네 수정되시면 돌아오겠습니다~~ ㅋㅋ

2024-09-23 16:10 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/AnnouncementRepository.kt
> +    suspend fun getAnnouncement(): Result<List<Announcement>?>
runcating 반환값이 result잖아요. 그래서 저는 뷰모델에서 말고 repository에서 검사하는게 더 구조적으로 안전하다고 생각해서 요렇게 했습니다. 
만약에 okhttp 예외같은게 나왔는데 뷰모델에서 처리하게되면 presentation레이어가 okhttp에 대한 종속성을 가지게 되는거잖아요. 그래서 data에서 검사해준다면 이를 다른 예외로 치환해서 presentation레이어가 불필요한 종속성을 갖는걸 막을 수 있다고 생각합니다.

2024-09-23 16:13 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
> +        if (text == "오프로드 회원을 탈퇴하겠습니다.") {
회원탈퇴 검사는 앱에서 중요한 로직이잖아요. 그래서 이걸 뷰모델에서 처리해야 하나, 다른 곳에서 처리해야하나 고민하다가 질문으로 남겨두려고 뷰모델에 두었습니다. ㅎㅎ

2024-09-23 16:18 UTC, leeseokchan00 commented on core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
> +        val updateAt: String,
언제 업데이트 되었는지 알려주는 변수입니다.

2024-09-23 16:19 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/di/UseCaseModule.kt
> +    ): GetAnnouncementUseCase {
아이고.. 수정했습니다.

2024-09-23 16:19 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/AnnouncementRepository.kt
> +    suspend fun getAnnouncement(): Result<List<Announcement>?>
오 꽤나 합리적인 답변이라고 생각되네요! 근데 그렇게 되면 프로젝트의 전반적인 data와 repository의 구조를 수정해야 하는데, 서버 측에서도 조만간 도메인이 수정될 예정이니 어떻게 처리하면 좋을지 조사한 뒤에 한번쯤 의논해보면 좋을 것 같습니다

2024-09-23 16:20 UTC, junseo511 commented on core/navigation/src/main/java/com/teamoffroad/core/navigation/RouteModel.kt
> +        val updateAt: String,
그러면 at이라는 말보다 다른 표현이 더 적절하지 않을까 싶습니다!!

2024-09-23 16:20 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/mapper/AnnouncementMapper.kt
> +    run {
누가 이렇게 만들어놨어서 이렇게 했는데, run 빼도 될 것 같아요

2024-09-23 16:21 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/AnnouncementResponseDto.kt
> +
ㅎㅎㅎ 수정했습니다.

2024-09-23 16:21 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/remote/response/AnnouncementResponseDto.kt
> +
수정했습니다.

2024-09-23 16:21 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
> +        if (text == "오프로드 회원을 탈퇴하겠습니다.") {
아 ViewModel이었군요 o0o 사실 이 부분에 대해서 저도 종종 생각하기는 하는데 정확한 답은 모르겠어요!! 상수화를 어떻게 해놓으면 좋을 것 같기는 한데 좋은 방안이 떠오르면 알려주시면 감사하겠습니다 🤔

2024-09-23 16:57 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/domain/repository/AnnouncementRepository.kt
> +    suspend fun getAnnouncement(): Result<List<Announcement>?>
첫번째 질문도 data에서 검사를 하게되면서 생긴것 같은데 수정가능 할 것 같습니다. !!

2024-09-23 16:57 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementDetailScreen.kt
> +    return Triple(year, month, day)
감사힙니다ㅎㅎ

2024-09-23 16:57 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementViewModel.kt
> +    fun getAnnouncement() {
음 네이밍 다시 생각해볼게요잉

2024-09-23 16:58 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/SettingViewModel.kt
> +        }
수정하겠습니다.

2024-09-25 07:11 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementViewModel.kt
> +    fun patchAnnouncement() {
c: 1. patch는 서버 통신때 쓰는 용어라 updateAnnouncement가 적당할 듯 싶습니다!! / 2. 다른 뷰모델에서도 update로 통일이 되어있어서 통일감을 주는편이 좋을듯요?!

2024-09-25 07:12 UTC, junseo511 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/AnnouncementRepositoryImpl.kt
> +            val announcementList = announcement!!.announcements.map {
c: ?:를 활용해보세요!! `!!` 는 앱의 안정성을 떨어뜨립니다 ㅎ하핫

2024-09-25 08:58 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/presentation/AnnouncementViewModel.kt
> +    fun patchAnnouncement() {
참고해서 수정했습니다.

2024-09-25 09:00 UTC, leeseokchan00 commented on feature/mypage/src/main/java/com/teamoffroad/feature/mypage/data/repository/AnnouncementRepositoryImpl.kt
> +            val announcementList = announcement!!.announcements.map {
위에서 말했던 data 레이어에서 null 검사를 끝냈기 때문에 !!를 사용해도 되겠다고 생각했는데, 엘비스 연산자를 쓰는게 더 안정적일 것 같네요. 많은 도움이 되었습니다.ㅎㅎㅎ👍

2024-09-25 09:40 UTC, junseo511 approved these changes

2024-09-25 12:41 UTC, merged